#!/usr/bin/env bash
set -euo pipefail

# Anthonyware — Collect Install Inputs & Setup
# Prompts for minimal operator inputs, creates/configures user, grants sudo, and sets passwords.

TARGET_USER_DEFAULT="${SUDO_USER:-${USER}}"
CURRENT_HOSTNAME="$(hostnamectl --static 2>/dev/null || hostname)"
TARGET_HOME_DEFAULT="$(getent passwd "$TARGET_USER_DEFAULT" | cut -d: -f6)"

LOG_DIR_DEFAULT="${TARGET_HOME_DEFAULT}/anthonyware-logs"
ANSWERS_FILE_DEFAULT="${LOG_DIR_DEFAULT}/install-answers.env"
ANSWERS_FILE="${ANSWERS_FILE:-$ANSWERS_FILE_DEFAULT}"
ALLOW_CREATE_USER="${ALLOW_CREATE_USER:-0}"

mkdir -p "$(dirname "$ANSWERS_FILE")"

read -r -p "Enter username to configure [${TARGET_USER_DEFAULT}]: " TARGET_USER_INPUT || true
TARGET_USER="${TARGET_USER_INPUT:-$TARGET_USER_DEFAULT}"

# Check if user exists; if not, optionally create
if ! id -u "$TARGET_USER" >/dev/null 2>&1; then
  echo "[WARN] User '${TARGET_USER}' does not exist."
  if [[ "$ALLOW_CREATE_USER" == "1" ]]; then
    echo "Creating user ${TARGET_USER}..."
    sudo useradd -m -s /bin/bash "$TARGET_USER" || true
  else
    read -r -p "Create user '${TARGET_USER}' now? [y/N]: " CREATE_USER || true
    if [[ "${CREATE_USER,,}" == "y" || "${CREATE_USER,,}" == "yes" ]]; then
      echo "Creating user ${TARGET_USER}..."
      sudo useradd -m -s /bin/bash "$TARGET_USER" || true
    else
      echo "User must exist to proceed; exiting."
      exit 1
    fi
  fi
fi

# Derive home; if missing, attempt to getent
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)" || TARGET_HOME="$TARGET_HOME_DEFAULT"

# Grant sudo permissions (add to sudoers with NOPASSWD for wheel group or create entry)
if ! sudo -u "$TARGET_USER" -n true 2>/dev/null; then
  echo "[WARN] User '${TARGET_USER}' does not have passwordless sudo."
  read -r -p "Grant sudo (NOPASSWD) to '${TARGET_USER}'? [y/N]: " GRANT_SUDO || true
  if [[ "${GRANT_SUDO,,}" == "y" || "${GRANT_SUDO,,}" == "yes" ]]; then
    echo "Adding ${TARGET_USER} to sudoers..."
    # Use usermod to add to wheel group if it exists, else create sudoers entry
    if grep -q "^wheel:" /etc/group 2>/dev/null; then
      sudo usermod -aG wheel "$TARGET_USER" || true
      echo "Added ${TARGET_USER} to wheel group"
    else
      # Fallback: add direct sudoers entry
      echo "${TARGET_USER} ALL=(ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/${TARGET_USER}" >/dev/null
      sudo chmod 0440 "/etc/sudoers.d/${TARGET_USER}"
      echo "Created sudoers entry for ${TARGET_USER}"
    fi
  fi
fi

read -r -p "Enter hostname for this machine [${CURRENT_HOSTNAME}]: " HOSTNAME_INPUT || true
HOSTNAME_VALUE="${HOSTNAME_INPUT:-$CURRENT_HOSTNAME}"

echo "Writing answers to: ${ANSWERS_FILE}"
cat > "$ANSWERS_FILE" <<EOF
# Generated by collect-input.sh
TARGET_USER=${TARGET_USER}
TARGET_HOME=${TARGET_HOME}
HOSTNAME=${HOSTNAME_VALUE}
REPO_PATH=${TARGET_HOME}/anthonyware
EOF

# Optionally apply hostname change now
read -r -p "Apply hostname change now? [y/N]: " APPLY_HOST || true
if [[ "${APPLY_HOST,,}" == "y" || "${APPLY_HOST,,}" == "yes" ]]; then
  if command -v hostnamectl >/dev/null 2>&1; then
    sudo hostnamectl set-hostname "$HOSTNAME_VALUE" || true
    echo "Hostname set to ${HOSTNAME_VALUE}"
  else
    echo "hostnamectl not available; skipping"
  fi
fi

# Optionally set root password
read -r -p "Set root password? [y/N]: " SET_ROOT_PW || true
if [[ "${SET_ROOT_PW,,}" == "y" || "${SET_ROOT_PW,,}" == "yes" ]]; then
  echo "Setting root password (input not logged)..."
  sudo passwd root || true
fi

# Optionally set password for TARGET_USER
read -r -p "Set password for '${TARGET_USER}'? [y/N]: " SET_PW || true
if [[ "${SET_PW,,}" == "y" || "${SET_PW,,}" == "yes" ]]; then
  echo "Setting password for ${TARGET_USER} (input not logged)..."
  sudo passwd "$TARGET_USER" || true
fi

echo "[INFO] Setup complete. Answers saved to ${ANSWERS_FILE}"

# Export for current shell when sourced
export TARGET_USER TARGET_HOME HOSTNAME REPO_PATH
